language: python

python:
    - 3.6

install:
  - pip install -r requirements.txt

script:
  - doc8 source/
  - make html SPHINXOPTS="-W -E"
  - make linkcheck
  - bash <(curl -s https://raw.githubusercontent.com/Peque/mrchecks/master/no_fixups)

notifications:
  email: false
